server {
    listen 80;
    server_name logi.dosutech.site;

    root /home/dosulogi/frontend/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }
}
